//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Editor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_Settings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network_Settings()
        {
            this.Network_Ports = new HashSet<Network_Ports>();
        }
    
        public int ID { get; set; }
        public int C_Version { get; set; }
        public string C_IP { get; set; }
        public int C_Subnet_Mask { get; set; }
        public string C_Default_Gateway { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network_Ports> Network_Ports { get; set; }
        public virtual Network_Versions Network_Versions { get; set; }
    }
}
