//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Editor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Network_SchemeEntities : DbContext
    {
        public Network_SchemeEntities(string conn_string)
            : base(conn_string)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Network_Connections> Network_Connections { get; set; }
        public virtual DbSet<Network_Hardware> Network_Hardware { get; set; }
        public virtual DbSet<Network_Ports> Network_Ports { get; set; }
        public virtual DbSet<Network_Settings> Network_Settings { get; set; }
        public virtual DbSet<Network_Versions> Network_Versions { get; set; }
    }
}
