//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Editor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_Ports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network_Ports()
        {
            this.Network_Connections = new HashSet<Network_Connections>();
            this.Network_Connections1 = new HashSet<Network_Connections>();
        }
    
        public int ID { get; set; }
        public int C_Version { get; set; }
        public bool C_Status { get; set; }
        public int C_Settings_ID { get; set; }
        public int C_Hardware_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network_Connections> Network_Connections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network_Connections> Network_Connections1 { get; set; }
        public virtual Network_Hardware Network_Hardware { get; set; }
        public virtual Network_Versions Network_Versions { get; set; }
        public virtual Network_Settings Network_Settings { get; set; }
    }
}
