//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Editor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_Hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Network_Hardware()
        {
            this.Network_Ports = new HashSet<Network_Ports>();
        }
    
        public int ID { get; set; }
        public int C_Version { get; set; }
        public bool C_Status { get; set; }
        public string C_Name { get; set; }
        public int C_Type { get; set; }
        public int C_Interface_X { get; set; }
        public int C_Interface_Y { get; set; }
    
        public virtual Network_Versions Network_Versions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network_Ports> Network_Ports { get; set; }
    }
}
