//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_Editor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_Connections
    {
        public int ID { get; set; }
        public int C_Version { get; set; }
        public int C_From_Port_ID { get; set; }
        public int C_To_Port_ID { get; set; }
    
        public virtual Network_Versions Network_Versions { get; set; }
        public virtual Network_Ports Network_Ports { get; set; }
        public virtual Network_Ports Network_Ports1 { get; set; }
    }
}
